### ISSUE TITLE
on mobile view centralised fb section

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/keeveedentallab-web#38]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/30463117/229010867-2d2092d9-8658-47b2-93a8-2c0c6c28bd82.png">

**Comment by ChrsHnsn** [comment]
![mobile view centralised fb section (2) #38](https://user-images.githubusercontent.com/97533037/229452495-b9002192-01e6-41e6-a8c3-6fcdc0ac6124.png)
![mobile view centralised fb section #38](https://user-images.githubusercontent.com/97533037/229452508-0228c245-1c1e-491d-8dd4-f8be2fe902a2.png)
